name: evcilhayvantakip
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\pets.png
    - assets\images\Anasayfa.png
    - assets\images\detailpetsanddelete.png
    - assets\images\addfood.png
    - assets\images\detailaddnew.png
    - assets\images\addnewpets.png